services:
  - type: web
    name: invoiceflow
    runtime: python
    pythonVersion: 3.11
    plan: standard
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn invoiceflow.wsgi -c gunicorn.conf.py
    envVars:
      - key: PRODUCTION
        value: "true"
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: invoiceflow.com.ng,www.invoiceflow.com.ng,api.invoiceflow.com.ng
