# Generated by Django 6.0.1 on 2026-01-31 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('device_type', models.CharField(default='desktop', max_length=20)),
                ('is_trusted', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='securityevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_activity']},
        ),
        migrations.AddField(
            model_name='mfaprofile',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mfaprofile',
            name='recovery_codes_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(default='desktop', max_length=20),
        ),
        migrations.AddField(
            model_name='usersession',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersession',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='role',
            field=models.CharField(default='member', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='token_type',
            field=models.CharField(choices=[('verify', 'Email Verification'), ('reset', 'Password Reset'), ('invite', 'Workspace Invitation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mfaprofile',
            name='secret',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', 'event_type', '-created_at'], name='invoices_se_user_id_d64872_idx'),
        ),
        migrations.AddField(
            model_name='knowndevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', '-created_at'], name='invoices_lo_ip_addr_7cd4ec_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', '-created_at'], name='invoices_lo_usernam_5946b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowndevice',
            unique_together={('user', 'fingerprint')},
        ),
    ]
