# Generated by Django 6.0.1 on 2026-02-01 12:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_userprofile_business_type_userprofile_invoice_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accent_color',
            field=models.CharField(default='#10b981', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accept_bank_transfers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accept_card_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accept_mobile_money',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_routing_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_swift_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='customers_import_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='customers_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_format',
            field=models.CharField(default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_invoice_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invoice_numbering_format',
            field=models.CharField(default='{prefix}-{year}-{number:04d}', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invoice_start_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invoices_import_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invoices_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locale',
            field=models.CharField(default='en-NG', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='products_import_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='products_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('ng', 'Nigeria'), ('us', 'United States'), ('gb', 'United Kingdom'), ('eu', 'European Union'), ('za', 'South Africa'), ('gh', 'Ghana'), ('ke', 'Kenya'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_color',
            field=models.CharField(default='#8b5cf6', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_id_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_invites_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vat_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wht_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wht_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('freelancer', 'Freelancer / Sole Proprietor'), ('agency', 'Agency / Studio'), ('consulting', 'Consulting Firm'), ('ecommerce', 'E-commerce / Retail'), ('saas', 'SaaS / Software'), ('services', 'Professional Services'), ('construction', 'Construction / Trades'), ('healthcare', 'Healthcare / Medical'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_currency',
            field=models.CharField(choices=[('NGN', '₦ - Nigerian Naira'), ('USD', '$ - US Dollar'), ('EUR', '€ - Euro'), ('GBP', '£ - British Pound'), ('ZAR', 'R - South African Rand'), ('GHS', '₵ - Ghanaian Cedi'), ('KES', 'KSh - Kenyan Shilling')], default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='invoice_style',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimal', 'Minimal'), ('professional', 'Professional'), ('bold', 'Bold')], default='modern', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Africa/Lagos', max_length=63),
        ),
    ]
