# Generated by Django 6.0.1 on 2026-02-01 13:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_onboarding_extended_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='company_logos/')),
                ('business_type', models.CharField(blank=True, choices=[('freelancer', 'Freelancer / Sole Proprietor'), ('agency', 'Agency / Studio'), ('consulting', 'Consulting Firm'), ('ecommerce', 'E-commerce / Retail'), ('saas', 'SaaS / Software'), ('services', 'Professional Services'), ('construction', 'Construction / Trades'), ('healthcare', 'Healthcare / Medical'), ('other', 'Other')], max_length=100)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=50)),
                ('business_address', models.TextField(blank=True)),
                ('business_city', models.CharField(blank=True, max_length=100)),
                ('business_state', models.CharField(blank=True, max_length=100)),
                ('business_country', models.CharField(blank=True, choices=[('ng', 'Nigeria'), ('us', 'United States'), ('gb', 'United Kingdom'), ('eu', 'European Union'), ('za', 'South Africa'), ('gh', 'Ghana'), ('ke', 'Kenya'), ('other', 'Other')], max_length=100)),
                ('business_postal_code', models.CharField(blank=True, max_length=20)),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('accent_color', models.CharField(default='#10b981', max_length=7)),
                ('invoice_style', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimal', 'Minimal'), ('professional', 'Professional'), ('bold', 'Bold')], default='modern', max_length=50)),
                ('tax_id_number', models.CharField(blank=True, max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file', models.FileField(upload_to='imports/')),
                ('error_report', models.FileField(blank=True, null=True, upload_to='import_errors/')),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='invoices.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.workspace'),
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('onboarding_step', models.IntegerField(default=1)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='invoices.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
