from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0004_recurring_billing_rebuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon name/class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_tax_deductible', models.BooleanField(default=False, help_text='Whether expenses in this category are tax deductible')),
                ('gl_account_code', models.CharField(blank=True, help_text='General ledger account code', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='invoices.expensecategory')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='invoices.workspace')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'verbose_name_plural': 'Expense categories',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Vendor tax ID/VAT number', max_length=50)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g., Net 30, Due on receipt', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('expense_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.expensecategory')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='invoices.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('expense_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Pre-tax amount', max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Amount including tax', max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('ZAR', 'South African Rand'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi')], default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate to base currency', max_digits=12)),
                ('base_currency_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount in workspace base currency', max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('petty_cash', 'Petty Cash'), ('company_card', 'Company Card'), ('other', 'Other')], default='other', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Receipt/invoice number from vendor', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reimbursed', 'Reimbursed'), ('billed', 'Billed to Client')], db_index=True, default='draft', max_length=20)),
                ('is_billable', models.BooleanField(default=False, help_text='Whether this expense can be billed to a client')),
                ('is_billed', models.BooleanField(default=False)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Markup percentage when billing to client', max_digits=5)),
                ('billable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to bill client (including markup)', max_digits=15)),
                ('project_name', models.CharField(blank=True, help_text='Optional project or job reference', max_length=255)),
                ('billed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for filtering')),
                ('is_recurring', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('reimbursed_at', models.DateTimeField(blank=True, null=True)),
                ('reimbursement_reference', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='invoices.expensecategory')),
                ('client', models.ForeignKey(blank=True, help_text='Client to bill for this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='invoices.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, help_text='Invoice where this expense was billed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_expenses', to='invoices.invoice')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_expenses', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='invoices.vendor')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='invoices.workspace')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('original_file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Storage path or URL', max_length=500)),
                ('file_type', models.CharField(choices=[('receipt', 'Receipt'), ('invoice', 'Invoice'), ('contract', 'Contract'), ('other', 'Other')], default='receipt', max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary receipt image')),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
                ('ocr_text', models.TextField(blank=True, help_text='OCR extracted text from receipt')),
                ('ocr_processed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='invoices.expense')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Expense Created'), ('updated', 'Expense Updated'), ('submitted', 'Expense Submitted'), ('approved', 'Expense Approved'), ('rejected', 'Expense Rejected'), ('reimbursed', 'Expense Reimbursed'), ('billed', 'Expense Billed to Client'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed'), ('deleted', 'Expense Deleted')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='invoices.expense')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_category_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_vendor_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['workspace', 'status'], name='invoices_ex_workspa_a1b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['workspace', 'expense_date'], name='invoices_ex_workspa_d4e5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['workspace', 'category'], name='invoices_ex_workspa_g7h8i9_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['workspace', 'is_billable', 'is_billed'], name='invoices_ex_workspa_j0k1l2_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['client', 'is_billed'], name='invoices_ex_client__m3n4o5_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseauditlog',
            index=models.Index(fields=['expense', 'action'], name='invoices_ex_expense_p6q7r8_idx'),
        ),
    ]
