# Generated by Django 6.0.1 on 2026-02-02 21:02

import django.db.models.deletion
import django.utils.timezone
import secrets
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_expense_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('provider_dispute_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired'), ('invoiced', 'Invoiced'), ('void', 'Void')], db_index=True, default='draft', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('NGN', '₦ - Nigerian Naira'), ('USD', '$ - US Dollar'), ('EUR', '€ - Euro'), ('GBP', '£ - British Pound'), ('ZAR', 'R - South African Rand'), ('GHS', '₵ - Ghanaian Cedi'), ('KES', 'KSh - Kenyan Shilling'), ('CAD', '$ - Canadian Dollar'), ('AUD', '$ - Australian Dollar'), ('INR', '₹ - Indian Rupee')], default='NGN', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('client_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('public_token', models.CharField(db_index=True, default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sort_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('provider_payout_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('report_params', models.JSONField(blank=True, default=dict)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel')], max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedReportLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('report_type', models.CharField(choices=[('revenue', 'Revenue Report'), ('aging', 'A/R Aging Report'), ('cashflow', 'Cash Flow Report'), ('profitability', 'Client Profitability'), ('tax', 'Tax Summary'), ('expense', 'Expense Report'), ('custom', 'Custom Report')], max_length=50)),
                ('report_params', models.JSONField(blank=True, default=dict, help_text='Report parameters like date range, filters')),
                ('name', models.CharField(blank=True, help_text='Optional name for the shared report', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('password_hash', models.CharField(blank=True, help_text='SHA256 hash of password if protected', max_length=64, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('chargeback', 'Chargeback'), ('payout', 'Payout')], default='payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('NGN', '₦ - Nigerian Naira'), ('USD', '$ - US Dollar'), ('EUR', '€ - Euro'), ('GBP', '£ - British Pound'), ('ZAR', 'R - South African Rand'), ('GHS', '₵ - Ghanaian Cedi'), ('KES', 'KSh - Kenyan Shilling'), ('CAD', '$ - Canadian Dollar'), ('AUD', '$ - Australian Dollar'), ('INR', '₹ - Indian Rupee')], default='USD', max_length=3)),
                ('status', models.CharField(default='succeeded', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='invoiceattachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoicepayment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.RemoveConstraint(
            model_name='expensecategory',
            name='unique_category_per_workspace',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='unique_vendor_per_workspace',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='invoices_ex_workspa_5c6325_idx',
            old_name='invoices_ex_workspa_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='invoices_ex_workspa_36d016_idx',
            old_name='invoices_ex_workspa_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='invoices_ex_workspa_d1d043_idx',
            old_name='invoices_ex_workspa_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='invoices_ex_workspa_fe5366_idx',
            old_name='invoices_ex_workspa_j0k1l2_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='invoices_ex_client__2c0427_idx',
            old_name='invoices_ex_client__m3n4o5_idx',
        ),
        migrations.RenameIndex(
            model_name='expenseauditlog',
            new_name='invoices_ex_expense_dfe502_idx',
            old_name='invoices_ex_expense_p6q7r8_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_workspa_315b58_idx',
            old_name='invoices_in_workspa_idx01',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_workspa_39e359_idx',
            old_name='invoices_in_workspa_idx02',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_client__d0ba52_idx',
            old_name='invoices_in_client_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentattempt',
            new_name='invoices_pa_executi_f7b399_idx',
            old_name='invoices_pa_executi_5g6h7i_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringschedule',
            new_name='invoices_re_status_ab1533_idx',
            old_name='invoices_re_status_a3b4c5_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringschedule',
            new_name='invoices_re_workspa_67c63b_idx',
            old_name='invoices_re_workspa_d6e7f8_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringscheduleauditlog',
            new_name='invoices_re_schedul_bcec4d_idx',
            old_name='invoices_re_schedul_8j9k0l_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduleexecution',
            new_name='invoices_sc_schedul_c06b6d_idx',
            old_name='invoices_sc_schedul_9a0b1c_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduleexecution',
            new_name='invoices_sc_schedul_ead489_idx',
            old_name='invoices_sc_schedul_2d3e4f_idx',
        ),
        migrations.RemoveField(
            model_name='invoiceattachment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoiceattachment',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='invoiceattachment',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='invoiceattachment',
            name='is_visible_to_client',
        ),
        migrations.RemoveField(
            model_name='invoiceattachment',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='invoiceattachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='is_partial',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('NGN', '₦ - Nigerian Naira'), ('USD', '$ - US Dollar'), ('EUR', '€ - Euro'), ('GBP', '£ - British Pound'), ('ZAR', 'R - South African Rand'), ('GHS', '₵ - Ghanaian Cedi'), ('KES', 'KSh - Kenyan Shilling'), ('CAD', '$ - Canadian Dollar'), ('AUD', '$ - Australian Dollar'), ('INR', '₹ - Indian Rupee')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.workspace'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('NGN', '₦ - Nigerian Naira'), ('USD', '$ - US Dollar'), ('EUR', '€ - Euro'), ('GBP', '£ - British Pound'), ('ZAR', 'R - South African Rand'), ('GHS', '₵ - Ghanaian Cedi'), ('KES', 'KSh - Kenyan Shilling'), ('CAD', '$ - Canadian Dollar'), ('AUD', '$ - Australian Dollar'), ('INR', '₹ - Indian Rupee')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_memo',
            field=models.TextField(blank=True, help_text='Visible to client on invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Private notes, not visible to client'),
        ),
        migrations.AlterField(
            model_name='invoiceattachment',
            name='file',
            field=models.FileField(upload_to='invoice_attachments/'),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='discount_type',
            field=models.CharField(default='flat', max_length=20),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='item_type',
            field=models.CharField(default='service', max_length=50),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='unit',
            field=models.CharField(default='unit', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('disputed', 'Disputed'), ('void', 'Void')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('workspace', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['public_token'], name='invoices_in_public__168f55_idx'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='invoices.payment'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='invoices.workspace'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='invoices.client'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='converted_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_estimate', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimate',
            name='parent_estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='invoices.estimate'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='invoices.workspace'),
        ),
        migrations.AddField(
            model_name='estimateactivity',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='invoices.estimate'),
        ),
        migrations.AddField(
            model_name='estimateactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.estimate'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='invoices.payment'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='invoices.workspace'),
        ),
        migrations.AddField(
            model_name='reportaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='invoices.workspace'),
        ),
        migrations.AddField(
            model_name='sharedreportlink',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shared_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedreportlink',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports', to='invoices.workspace'),
        ),
        migrations.AddField(
            model_name='reportaccesslog',
            name='shared_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='invoices.sharedreportlink'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='invoices.payment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invoices.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('workspace', 'estimate_number')},
        ),
        migrations.AddIndex(
            model_name='sharedreportlink',
            index=models.Index(fields=['token'], name='invoices_sh_token_ce1954_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedreportlink',
            index=models.Index(fields=['workspace', 'is_active'], name='invoices_sh_workspa_e0f779_idx'),
        ),
        migrations.AddIndex(
            model_name='reportaccesslog',
            index=models.Index(fields=['shared_link', '-accessed_at'], name='invoices_re_shared__8a960b_idx'),
        ),
    ]
