# Generated by Django 6.0.2 on 2026-02-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_clientportalsession_clientportaltoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientportalsession',
            name='device_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='clientportaltoken',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientportalsession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='clientportaltoken',
            name='token',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
