# Generated by Django 6.0.3 on 2026-03-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_clientportalsession_device_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date']},
        ),
    ]
