# Generated by Django 5.2.9 on 2025-12-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_gdpr_request_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
