# Generated by Django 5.2.9 on 2025-12-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_add_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paystack_account_name',
            field=models.CharField(blank=True, help_text='Account holder name (verified)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paystack_account_number',
            field=models.CharField(blank=True, help_text='Account number for receiving payments', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paystack_bank_code',
            field=models.CharField(blank=True, help_text='Bank code for the settlement account', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paystack_percentage_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee percentage (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paystack_settlement_bank',
            field=models.CharField(blank=True, help_text='Bank name for display', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paystack_subaccount_active',
            field=models.BooleanField(default=False, help_text='Whether direct payments are enabled'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, help_text='Paystack subaccount code for receiving direct payments', max_length=100, null=True),
        ),
    ]
