# Generated by Django 6.0.3 on 2026-03-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_usersession_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='currency',
            field=models.CharField(choices=[('NGN', '₦ - Nigerian Naira'), ('USD', '$ - US Dollar'), ('EUR', '€ - Euro'), ('GBP', '£ - British Pound'), ('ZAR', 'R - South African Rand'), ('GHS', '₵ - Ghanaian Cedi'), ('KES', 'KSh - Kenyan Shilling'), ('CAD', '$ - Canadian Dollar'), ('AUD', '$ - Australian Dollar'), ('INR', '₹ - Indian Rupee')], default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoiceactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Invoice Created'), ('updated', 'Invoice Updated'), ('sent', 'Invoice Sent'), ('viewed', 'Invoice Viewed'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('status_changed', 'Status Changed'), ('reminder_sent', 'Reminder Sent'), ('voided', 'Invoice Voided'), ('written_off', 'Invoice Written Off'), ('duplicated', 'Invoice Duplicated'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed'), ('comment_added', 'Comment Added'), ('downloaded', 'PDF Downloaded'), ('shared', 'Link Shared'), ('other', 'Other Activity')], max_length=50),
        ),
    ]
