# Generated by Django 5.2.9 on 2025-12-15 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_add_paystack_subaccount_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this account', max_length=200)),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('mobile_money', 'Mobile Money'), ('nuban', 'NUBAN'), ('ghipss', 'GHIPSS'), ('basa', 'BASA')], default='bank', max_length=20)),
                ('bank_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=30)),
                ('account_name', models.CharField(help_text='Verified account holder name', max_length=200)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('recipient_code', models.CharField(blank=True, help_text='Payment gateway recipient code', max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transfer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, help_text='Reason for transfer', max_length=200)),
                ('gateway_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='invoices.paymentrecipient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_card_payments', models.BooleanField(default=True)),
                ('enable_bank_transfers', models.BooleanField(default=True)),
                ('enable_mobile_money', models.BooleanField(default=False)),
                ('enable_ussd', models.BooleanField(default=False)),
                ('preferred_currency', models.CharField(default='NGN', max_length=3)),
                ('auto_payout', models.BooleanField(default=False, help_text='Automatically transfer funds to default recipient')),
                ('payout_schedule', models.CharField(choices=[('auto', 'Automatic (Next Business Day)'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual Withdrawal')], default='auto', max_length=20)),
                ('payout_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Minimum amount before auto-payout', max_digits=12)),
                ('send_payment_receipt', models.BooleanField(default=True)),
                ('send_payout_notification', models.BooleanField(default=True)),
                ('payment_instructions', models.TextField(blank=True, help_text='Custom payment instructions for clients')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('channel', models.CharField(blank=True, choices=[('card', 'Card Payment'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('qr', 'QR Code'), ('mobile_money', 'Mobile Money'), ('direct_debit', 'Direct Debit')], max_length=20, null=True)),
                ('gateway', models.CharField(default='paystack', max_length=50)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('authorization_code', models.CharField(blank=True, max_length=100, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_exp_month', models.CharField(blank=True, max_length=2, null=True)),
                ('card_exp_year', models.CharField(blank=True, max_length=4, null=True)),
                ('card_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subaccount_code', models.CharField(blank=True, max_length=100, null=True)),
                ('split_code', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('gateway_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_payment_user_created'), models.Index(fields=['invoice', 'status'], name='idx_payment_invoice_status'), models.Index(fields=['reference'], name='idx_payment_reference'), models.Index(fields=['status', '-created_at'], name='idx_payment_status_date')],
            },
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=50)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.CharField(max_length=2)),
                ('exp_year', models.CharField(max_length=4)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('reusable', models.BooleanField(default=True)),
                ('signature', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('nickname', models.CharField(blank=True, help_text='Friendly name for this card', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_card_user_active')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentrecipient',
            index=models.Index(fields=['user', 'is_active'], name='idx_recipient_user_active'),
        ),
        migrations.AddIndex(
            model_name='paymentrecipient',
            index=models.Index(fields=['user', 'is_primary'], name='idx_recipient_user_primary'),
        ),
        migrations.AddIndex(
            model_name='paymentpayout',
            index=models.Index(fields=['user', '-created_at'], name='idx_payout_user_created'),
        ),
        migrations.AddIndex(
            model_name='paymentpayout',
            index=models.Index(fields=['status', '-created_at'], name='idx_payout_status_date'),
        ),
    ]
