# Generated by Django 6.0.3 on 2026-03-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_fix_missing_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedreportlink',
            name='password_hash',
            field=models.CharField(blank=True, help_text='PBKDF2 hash of password if protected', max_length=255, null=True),
        ),
    ]
