# Generated by Django 5.2.9 on 2025-12-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_payment_reconciliation_recovery_kyc'),
    ]

    operations = [
    ]
