# Generated by Django 6.0.3 on 2026-04-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_fix_shared_report_password_hash_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('NGN', '₦ - Nigerian Naira'), ('USD', '$ - US Dollar'), ('EUR', '€ - Euro'), ('GBP', '£ - British Pound'), ('ZAR', 'R - South African Rand'), ('GHS', '₵ - Ghanaian Cedi'), ('KES', 'KSh - Kenyan Shilling'), ('CAD', '$ - Canadian Dollar'), ('AUD', '$ - Australian Dollar'), ('INR', '₹ - Indian Rupee')], default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('NGN', '₦ - Nigerian Naira'), ('USD', '$ - US Dollar'), ('EUR', '€ - Euro'), ('GBP', '£ - British Pound'), ('ZAR', 'R - South African Rand'), ('GHS', '₵ - Ghanaian Cedi'), ('KES', 'KSh - Kenyan Shilling'), ('CAD', '$ - Canadian Dollar'), ('AUD', '$ - Australian Dollar'), ('INR', '₹ - Indian Rupee')], default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
    ]
