# Generated by Django 5.2.9 on 2025-12-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_add_recurring_and_public_invoice_safety'),
    ]

    operations = [
    ]
