# Generated by Django 6.0.3 on 2026-04-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_update_currency_defaults_to_ngn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('NGN', '₦ - Nigerian Naira'), ('USD', '$ - US Dollar'), ('EUR', '€ - Euro'), ('GBP', '£ - British Pound'), ('ZAR', 'R - South African Rand'), ('GHS', '₵ - Ghanaian Cedi'), ('KES', 'KSh - Kenyan Shilling'), ('CAD', '$ - Canadian Dollar'), ('AUD', '$ - Australian Dollar'), ('INR', '₹ - Indian Rupee')], default='NGN', max_length=3),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['workspace', 'name'], name='invoices_cl_workspa_d5b31d_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['workspace', 'email'], name='invoices_cl_workspa_bc8a39_idx'),
        ),
    ]
