# Generated by Django 5.2.9 on 2025-12-22 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_add_invoice_brand_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('email_type', models.CharField(choices=[('verification', 'Email Verification'), ('invoice_ready', 'Invoice Ready'), ('payment_reminder', 'Payment Reminder'), ('payment_receipt', 'Payment Receipt'), ('recurring_notification', 'Recurring Notification'), ('security_alert', 'Security Alert'), ('password_reset', 'Password Reset')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('queued', 'Queued')], default='queued', max_length=20)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('bounce_type', models.CharField(blank=True, max_length=50)),
                ('bounce_reason', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailRetryQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('retry_strategy', models.CharField(choices=[('exponential', 'Exponential Backoff'), ('linear', 'Linear Backoff'), ('immediate', 'Immediate Retry')], default='exponential', max_length=20)),
                ('next_retry_at', models.DateTimeField()),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_retry_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('process_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_data', models.JSONField(default=dict)),
                ('http_status', models.PositiveIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicInvoiceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('max_accesses', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringInvoiceExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringInvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_marketing_emails', models.BooleanField(default=False)),
                ('allow_security_alerts', models.BooleanField(default=True)),
                ('invoice_reminders_enabled', models.BooleanField(default=True)),
                ('payment_notifications_enabled', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_method', models.CharField(blank=True, choices=[('totp', 'TOTP'), ('email', 'Email')], default='totp', max_length=20)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('preferred_timezone', models.CharField(default='UTC', max_length=63)),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=20)),
                ('data_retention_days', models.PositiveIntegerField(default=365)),
                ('auto_export_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.CreateModel(
            name='UserSettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('accessed', 'Accessed')], max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='gdprrequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='gdprrequest',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mfaprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymentcard',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentrecipient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentsettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processedwebhook',
            options={},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_seen']},
        ),
        migrations.AlterModelOptions(
            name='waitlist',
            options={'ordering': ['-subscribed_at']},
        ),
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='idx_email_token',
        ),
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='idx_user_token_type',
        ),
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='idx_token_expires',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='idx_user_status',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='idx_user_created',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='idx_user_date',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='idx_invoice_id',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='idx_user_client',
        ),
        migrations.RemoveIndex(
            model_name='loginattempt',
            name='idx_login_user_time',
        ),
        migrations.RemoveIndex(
            model_name='loginattempt',
            name='idx_login_ip_time',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='idx_payment_user_created',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='idx_payment_invoice_status',
        ),
        migrations.RemoveIndex(
            model_name='paymentpayout',
            name='idx_payout_user_created',
        ),
        migrations.RemoveIndex(
            model_name='paymentpayout',
            name='idx_payout_status_date',
        ),
        migrations.RemoveIndex(
            model_name='paymentrecipient',
            name='idx_recipient_user_primary',
        ),
        migrations.RemoveIndex(
            model_name='processedwebhook',
            name='idx_webhook_provider_event',
        ),
        migrations.RemoveIndex(
            model_name='processedwebhook',
            name='idx_webhook_processed',
        ),
        migrations.RemoveIndex(
            model_name='recurringinvoice',
            name='idx_recurring_schedule',
        ),
        migrations.RemoveIndex(
            model_name='socialaccount',
            name='idx_social_provider',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='idx_user_session_activity',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='invoices_co_status_770f49_idx',
            old_name='idx_contact_status',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='invoices_co_email_8c2135_idx',
            old_name='idx_contact_email',
        ),
        migrations.RenameIndex(
            model_name='invoicetemplate',
            new_name='invoices_in_user_id_771af9_idx',
            old_name='idx_template_user_default',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='invoices_pa_referen_6a2c36_idx',
            old_name='idx_payment_reference',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='invoices_pa_status_8ab6c7_idx',
            old_name='idx_payment_status_date',
        ),
        migrations.RenameIndex(
            model_name='paymentcard',
            new_name='invoices_pa_user_id_3146d4_idx',
            old_name='idx_card_user_active',
        ),
        migrations.RenameIndex(
            model_name='paymentrecipient',
            new_name='invoices_pa_user_id_db0947_idx',
            old_name='idx_recipient_user_active',
        ),
        migrations.RenameIndex(
            model_name='paymentreconciliation',
            new_name='invoices_pa_user_id_c06bc3_idx',
            old_name='invoices_pa_user_id_9f7b6e_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreconciliation',
            new_name='invoices_pa_status_f2a00b_idx',
            old_name='invoices_pa_status_2c4e8b_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentrecovery',
            new_name='invoices_pa_user_id_4a3f90_idx',
            old_name='invoices_pa_user_id_7f8c9e_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentrecovery',
            new_name='invoices_pa_next_re_6814c8_idx',
            old_name='invoices_pa_next_re_3a2b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringinvoice',
            new_name='invoices_re_user_id_53c00d_idx',
            old_name='idx_recurring_user_status',
        ),
        migrations.RenameIndex(
            model_name='socialaccount',
            new_name='invoices_so_user_id_a5b60f_idx',
            old_name='idx_social_user_provider',
        ),
        migrations.RenameIndex(
            model_name='useridentityverification',
            new_name='invoices_us_status_e6bdab_idx',
            old_name='invoices_us_status_1a5c7d_idx',
        ),
        migrations.RenameIndex(
            model_name='useridentityverification',
            new_name='invoices_us_user_id_f65377_idx',
            old_name='invoices_us_user_id_3f7b2e_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='invoices_us_session_e480bd_idx',
            old_name='idx_session_key',
        ),
        migrations.RenameIndex(
            model_name='waitlist',
            new_name='invoices_wa_feature_ad470a_idx',
            old_name='idx_waitlist_feature',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='brand_color',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='recurring_invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='authorization_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_bank',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_exp_month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_exp_year',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway_response',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='split_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subaccount_code',
        ),
        migrations.RemoveField(
            model_name='paymentpayout',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='paymentpayout',
            name='gateway_response',
        ),
        migrations.RemoveField(
            model_name='paymentpayout',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='paymentpayout',
            name='transfer_code',
        ),
        migrations.RemoveField(
            model_name='paymentpayout',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paymentrecipient',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='paymentrecipient',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='processedwebhook',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='processedwebhook',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='processedwebhook',
            name='payload_hash',
        ),
        migrations.RemoveField(
            model_name='processedwebhook',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='processedwebhook',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='location',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='os',
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentpayout',
            name='attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayout',
            name='failure_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentpayout',
            name='paystack_transfer_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentrecipient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='paymentrecipient',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentrecipient',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='accept_bank_transfers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='accept_cards',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='auto_reconcile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='default_currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='minimum_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='payout_delay_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='paystack_public_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='paystack_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoicetemplate'),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='token_scopes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(choices=[('sales', 'Sales Inquiry'), ('support', 'Technical Support'), ('billing', 'Billing Question'), ('feature', 'Feature Request'), ('bug', 'Bug Report'), ('general', 'General Inquiry')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token_type',
            field=models.CharField(choices=[('signup', 'Account Verification'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mfaprofile',
            name='backup_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mfaprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mfaprofile',
            name='secret_key',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='card_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='exp_month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='exp_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='reusable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentpayout',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.paymentrecipient'),
        ),
        migrations.AlterField(
            model_name='paymentpayout',
            name='reference',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentpayout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='auto_payout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='payment_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='payout_schedule',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual')], default='weekly', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='payout_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='processedwebhook',
            name='event_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recurringinvoice',
            name='client_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recurringinvoice',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringinvoice',
            name='next_generation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringinvoice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_invoice_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_invoice_overdue',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_invoice_viewed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_password_changes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_payment_received',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_security_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_weekly_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='paystack_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='paystack_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='paystack_bank_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='paystack_percentage_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='paystack_settlement_bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='paystack_subaccount_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', '-created_at'], name='invoices_lo_usernam_5946b9_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', '-created_at'], name='invoices_lo_ip_addr_7cd4ec_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentpayout',
            index=models.Index(fields=['user', 'status'], name='invoices_pa_user_id_11f48b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentpayout',
            index=models.Index(fields=['reference'], name='invoices_pa_referen_2323f0_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoice',
            index=models.Index(fields=['next_generation'], name='invoices_re_next_ge_f95c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-last_seen'], name='invoices_us_user_id_a52a23_idx'),
        ),
        migrations.AddField(
            model_name='emaildeliverylog',
            name='related_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='emaildeliverylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailretryqueue',
            name='email_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_queue', to='invoices.emaildeliverylog'),
        ),
        migrations.AddIndex(
            model_name='executionlock',
            index=models.Index(fields=['name', 'expires_at'], name='invoices_ex_name_339681_idx'),
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceaccesslog',
            name='accessed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceaccesslog',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='publicinvoicetoken',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_token', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='recurringinvoiceexecution',
            name='invoice_generated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_execution', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='recurringinvoiceexecution',
            name='recurring_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='invoices.recurringinvoice'),
        ),
        migrations.AddField(
            model_name='recurringinvoicelineitem',
            name='recurring_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.recurringinvoice'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_audit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersettingsauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GDPRRequest',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='token_expires',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='updated_at',
        ),
        migrations.AddIndex(
            model_name='emaildeliverylog',
            index=models.Index(fields=['user', 'status'], name='invoices_em_user_id_035d15_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildeliverylog',
            index=models.Index(fields=['to_email', '-created_at'], name='invoices_em_to_emai_27645e_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildeliverylog',
            index=models.Index(fields=['email_type', 'status'], name='invoices_em_email_t_5aef6a_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildeliverylog',
            index=models.Index(fields=['message_id'], name='invoices_em_message_c6e535_idx'),
        ),
        migrations.AddIndex(
            model_name='emailretryqueue',
            index=models.Index(fields=['is_active', 'next_retry_at'], name='invoices_em_is_acti_7e7ada_idx'),
        ),
        migrations.AddIndex(
            model_name='emailretryqueue',
            index=models.Index(fields=['email_log', 'is_active'], name='invoices_em_email_l_4aa907_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['user', '-created_at'], name='invoices_id_user_id_331012_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['key', '-created_at'], name='invoices_id_key_213024_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceaccesslog',
            index=models.Index(fields=['invoice', '-accessed_at'], name='invoices_in_invoice_cc7ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceaccesslog',
            index=models.Index(fields=['ip_address', '-accessed_at'], name='invoices_in_ip_addr_fdaa9e_idx'),
        ),
        migrations.AddIndex(
            model_name='publicinvoicetoken',
            index=models.Index(fields=['token', 'is_revoked'], name='invoices_pu_token_c38283_idx'),
        ),
        migrations.AddIndex(
            model_name='publicinvoicetoken',
            index=models.Index(fields=['invoice', 'expires_at'], name='invoices_pu_invoice_0ded05_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoiceexecution',
            index=models.Index(fields=['recurring_invoice', 'status'], name='invoices_re_recurri_2f25ef_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoiceexecution',
            index=models.Index(fields=['idempotency_key'], name='invoices_re_idempot_751459_idx'),
        ),
        migrations.AddIndex(
            model_name='usersettings',
            index=models.Index(fields=['user', 'updated_at'], name='invoices_us_user_id_0933c2_idx'),
        ),
        migrations.AddIndex(
            model_name='usersettingsauditlog',
            index=models.Index(fields=['user', '-created_at'], name='invoices_us_user_id_ab15c0_idx'),
        ),
        migrations.AddIndex(
            model_name='usersettingsauditlog',
            index=models.Index(fields=['action', '-created_at'], name='invoices_us_action_4f993a_idx'),
        ),
    ]
