# Generated by Django 5.2.9 on 2025-12-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_add_invoice_brand_name'),
    ]

    operations = [
    ]
