# Generated by Django 5.2.9 on 2025-12-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0027_enterprise_features'),
    ]

    operations = [
        # Note: Previous operations removed as SocialAccount model
        # was already modified to not have provider_id field
        # The model now uses user+provider as the unique constraint
    ]
