# Generated by Django 5.2.9 on 2025-12-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0028_add_enterprise_auth_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedwebhook',
            options={'ordering': ['-processed_at']},
        ),
        migrations.AlterField(
            model_name='processedwebhook',
            name='event_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='processedwebhook',
            index=models.Index(fields=['event_id'], name='invoices_pr_event_i_4b6a56_idx'),
        ),
        migrations.AddIndex(
            model_name='processedwebhook',
            index=models.Index(fields=['-processed_at'], name='invoices_pr_process_29835a_idx'),
        ),
    ]
