# Generated by Django 5.2.9 on 2025-12-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0030_alter_invoice_options_alter_socialaccount_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='socialaccount',
            name='invoices_so_user_id_a5b60f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=set(),
        ),
    ]
