# Generated by Django 5.2.9 on 2025-12-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0030_alter_invoice_options_alter_socialaccount_options_and_more'),
    ]

    operations = [
    ]
