# Generated by Django 5.2.9 on 2025-12-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0031_remove_socialaccount_invoices_so_user_id_a5b60f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='socialaccount',
            name='invoices_so_user_id_a5b60f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=set(),
        ),
    ]
