# Generated by Django 5.2.9 on 2025-12-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0032_remove_socialaccount_invoices_so_user_id_a5b60f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='paystack_account_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paystack_account_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paystack_bank_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paystack_percentage_charge',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paystack_settlement_bank',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paystack_subaccount_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paystack_subaccount_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paystack_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_name',
            field=models.CharField(default='VAT', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
