# Generated by Django 5.2.9 on 2025-12-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0033_remove_userprofile_paystack_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsettings',
            name='accept_bank_transfers',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='accept_cards',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paystack_subaccount_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
