# Generated by Django 5.2.9 on 2025-12-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0034_remove_paymentsettings_accept_bank_transfers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsettings',
            name='auto_reconcile',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='default_currency',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='minimum_payment_amount',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='payout_delay_days',
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='account_number_encrypted',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='paystack_webhook_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='auto_payout',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='payout_schedule',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='payout_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='preferred_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
