# Generated by Django 5.2.9 on 2026-01-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0035_remove_paymentsettings_auto_reconcile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsettings',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
