# Generated by Django 5.2.9 on 2026-01-03 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0037_invoice_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('remind_before_days', models.IntegerField(default=3)),
                ('remind_after_days', models.IntegerField(default=7)),
                ('reminder_subject', models.CharField(default='Payment Reminder: Invoice {invoice_id}', max_length=255)),
                ('reminder_body', models.TextField(default='Hi {client_name},\n\nThis is a friendly reminder that invoice {invoice_id} is due on {due_date}. Please let us know if you have any questions.\n\nBest regards,\n{business_name}')),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_delay_minutes', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutomatedReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('before_due', 'Before Due Date'), ('on_due', 'On Due Date'), ('after_due', 'After Due Date'), ('manual', 'Manual Reminder')], max_length=20)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('days_delta', models.IntegerField(default=0, help_text='Days relative to due date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_reminders', to='invoices.invoice')),
            ],
            options={
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['is_sent', 'scheduled_for'], name='invoices_au_is_sent_92de53_idx')],
            },
        ),
    ]
