# Generated by Django 5.2.9 on 2026-01-03 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0038_userremindersettings_automatedreminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userremindersettings',
            name='user',
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('before_due', 'Days Before Due Date'), ('on_due', 'On Due Date'), ('after_due', 'Days After Due Date'), ('upon_creation', 'Immediately Upon Creation')], default='after_due', max_length=20)),
                ('days_delta', models.IntegerField(default=0)),
                ('subject_template', models.CharField(blank=True, max_length=255)),
                ('body_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['trigger_type', 'days_delta'],
                'unique_together': {('user', 'trigger_type', 'days_delta')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reminders', to='invoices.invoice')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.reminderrule')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice')),
                ('scheduled_reminder', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log', to='invoices.scheduledreminder')),
            ],
        ),
        migrations.DeleteModel(
            name='AutomatedReminder',
        ),
        migrations.DeleteModel(
            name='UserReminderSettings',
        ),
        migrations.AddIndex(
            model_name='scheduledreminder',
            index=models.Index(fields=['status', 'scheduled_for'], name='invoices_sc_status_fb734f_idx'),
        ),
    ]
