# Generated by Django 5.2.9 on 2026-01-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0039_remove_userremindersettings_user_reminderrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderrule',
            name='exclude_weekends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminderrule',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='reminderrule',
            name='retry_on_failure',
            field=models.BooleanField(default=True),
        ),
    ]
