# Generated by Django 5.2.9 on 2026-01-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0040_reminderrule_exclude_weekends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderrule',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('sms', 'SMS')], default='email', max_length=20),
        ),
    ]
