# Generated by Django 5.2.9 on 2026-01-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0042_inappnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderrule',
            name='retry_delay',
            field=models.IntegerField(default=300),
        ),
    ]
