# Generated by Django 5.2.9 on 2026-01-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0043_reminderrule_retry_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderrule',
            name='attach_pdf',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reminderrule',
            name='custom_sender_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reminderrule',
            name='reply_to_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='scheduledreminder',
            name='delivery_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scheduledreminder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], default='pending', max_length=20),
        ),
    ]
