# Generated by Django 5.2.9 on 2026-01-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0045_reminderlog_clicked_at_reminderlog_opened_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='automated_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
