# Generated by Django 5.2.9 on 2026-01-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0046_invoice_automated_reminders_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_currency',
            field=models.CharField(choices=[('USD', '$ - US Dollar'), ('EUR', '€ - Euro'), ('GBP', '£ - British Pound'), ('NGN', '₦ - Nigerian Naira'), ('CAD', 'C$ - Canadian Dollar'), ('AUD', 'A$ - Australian Dollar'), ('INR', '₹ - Indian Rupee'), ('JPY', '¥ - Japanese Yen'), ('ZAR', 'R - South African Rand'), ('KES', 'KSh - Kenyan Shilling'), ('GHS', 'GH₵ - Ghanaian Cedi'), ('BTC', '₿ - Bitcoin'), ('ETH', 'Ξ - Ethereum')], default='USD', max_length=3),
        ),
    ]
