# Generated by Django 5.2.9 on 2026-01-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0047_alter_userprofile_default_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedWebhook',
        ),
    ]
