# Generated by Django 5.2.9 on 2026-01-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0048_delete_processedwebhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Unique event identifier from payment provider', max_length=100, unique=True)),
                ('provider', models.CharField(default='paystack', help_text='Payment provider (paystack, stripe, etc)', max_length=50)),
                ('event_type', models.CharField(blank=True, help_text='Event type (charge.success, etc)', max_length=100)),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Transaction reference', max_length=100)),
                ('payload_hash', models.CharField(blank=True, help_text='SHA256 hash of payload for integrity verification', max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Processed Webhook',
                'verbose_name_plural': 'Processed Webhooks',
                'ordering': ['-processed_at'],
                'indexes': [
                    models.Index(fields=['provider', 'event_id'], name='idx_webhook_provider_event'),
                    models.Index(fields=['-processed_at'], name='idx_webhook_processed'),
                ],
            },
        ),
    ]
