# Generated by Django 5.2.9 on 2026-01-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0049_reintroduce_processed_webhook"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialAccount",
        ),
    ]
