# Generated by Django 5.2.9 on 2026-01-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0051_add_payment_customer_email'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processedwebhook',
            new_name='invoices_pr_provide_8534f0_idx',
            old_name='idx_webhook_provider_event',
        ),
        migrations.RenameIndex(
            model_name='processedwebhook',
            new_name='invoices_pr_process_29835a_idx',
            old_name='idx_webhook_processed',
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider_id',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
