# Generated by Django 6.0.1 on 2026-01-29 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0052_rename_idx_webhook_provider_event_invoices_pr_provide_8534f0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='draft', max_length=10),
        ),
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('line_item_added', 'Line Item Added'), ('line_item_updated', 'Line Item Updated'), ('line_item_deleted', 'Line Item Deleted'), ('email_sent', 'Email Sent'), ('pdf_generated', 'PDF Generated'), ('deleted', 'Deleted')], max_length=30)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='invoices.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoice histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', '-created_at'], name='invoices_in_invoice_c0ae4e_idx'), models.Index(fields=['action', '-created_at'], name='invoices_in_action_485fcc_idx')],
            },
        ),
    ]
