# Generated by Django 6.0.1 on 2026-01-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0053_add_invoice_history_and_status_transitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reminder_rules',
            field=models.ManyToManyField(blank=True, related_name='custom_invoices', to='invoices.reminderrule'),
        ),
    ]
